server:
  port: 8080

spring:
  application:
    name: customer

  zipkin:
    base-url: http://localhost:9411


  datasource:
    username: 'admin'
    password: 'userpass'
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true


  rabbitmq:
    addresses: localhost:5673

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
